EDA And Feature Engineering on Fligh price prediction

FEATURES

The various features of the cleaned dataset are explained below:
1) Airline: The name of the airline company is stored in the airline column. It is a categorical feature having 6 different airlines.
2) Flight: Flight stores information regarding the plane's flight code. It is a categorical feature.
3) Source City: City from which the flight takes off. It is a categorical feature having 6 unique cities.
4) Departure Time: This is a derived categorical feature obtained created by grouping time periods into bins. It stores information about the departure time and have 6 unique time labels.
5) Stops: A categorical feature with 3 distinct values that stores the number of stops between the source and destination cities.
6) Arrival Time: This is a derived categorical feature created by grouping time intervals into bins. It has six distinct time labels and keeps information about the arrival time.
7) Destination City: City where the flight will land. It is a categorical feature having 6 unique cities.
8) Class: A categorical feature that contains information on seat class; it has two distinct values: Business and Economy.
9) Duration: A continuous feature that displays the overall amount of time it takes to travel between cities in hours.
10)Days Left: This is a derived characteristic that is calculated by subtracting the trip date by the booking date.
11) Price: Target variable stores information of the ticket price.

In [149]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [150]:
df = pd.read_csv('economy.csv')

df.head()

,date,airline,ch_code,num_code,dep_time,from,time_taken,stop,arr_time,to,price
0,11-02-2022,SpiceJet,SG,8709,18:55,Delhi,02h 10m,non-stop,21:05,Mumbai,"5,953"
1,11-02-2022,SpiceJet,SG,8157,06:20,Delhi,02h 20m,non-stop,08:40,Mumbai,"5,953"
2,11-02-2022,AirAsia,I5,764,04:25,Delhi,02h 10m,non-stop,06:35,Mumbai,"5,956"
3,11-02-2022,Vistara,UK,995,10:20,Delhi,02h 15m,non-stop,12:35,Mumbai,"5,955"
4,11-02-2022,Vistara,UK,963,08:50,Delhi,02h 20m,non-stop,11:10,Mumbai,"5,955"

In [151]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 206774 entries, 0 to 206773
Data columns (total 11 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   date        206774 non-null  str
 1   airline     206774 non-null  str
 2   ch_code     206774 non-null  str
 3   num_code    206774 non-null  int64
 4   dep_time    206774 non-null  str
 5   from        206774 non-null  str
 6   time_taken  206774 non-null  str
 7   stop        206774 non-null  str
 8   arr_time    206774 non-null  str
 9   to          206774 non-null  str
 10  price       206774 non-null  str
dtypes: int64(1), str(10)
memory usage: 17.4 MB

Feature Engneering

In [152]:
df['Date'] = df['date'].str.split('-').str[0]
df['Month'] = df['date'].str.split('-').str[1]
df['Year'] = df['date'].str.split('-').str[2]

df.head()

,date,airline,ch_code,num_code,dep_time,from,time_taken,stop,arr_time,to,price,Date,Month,Year
0,11-02-2022,SpiceJet,SG,8709,18:55,Delhi,02h 10m,non-stop,21:05,Mumbai,"5,953",11,02,2022
1,11-02-2022,SpiceJet,SG,8157,06:20,Delhi,02h 20m,non-stop,08:40,Mumbai,"5,953",11,02,2022
2,11-02-2022,AirAsia,I5,764,04:25,Delhi,02h 10m,non-stop,06:35,Mumbai,"5,956",11,02,2022
3,11-02-2022,Vistara,UK,995,10:20,Delhi,02h 15m,non-stop,12:35,Mumbai,"5,955",11,02,2022
4,11-02-2022,Vistara,UK,963,08:50,Delhi,02h 20m,non-stop,11:10,Mumbai,"5,955",11,02,2022

In [153]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 206774 entries, 0 to 206773
Data columns (total 14 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   date        206774 non-null  str
 1   airline     206774 non-null  str
 2   ch_code     206774 non-null  str
 3   num_code    206774 non-null  int64
 4   dep_time    206774 non-null  str
 5   from        206774 non-null  str
 6   time_taken  206774 non-null  str
 7   stop        206774 non-null  str
 8   arr_time    206774 non-null  str
 9   to          206774 non-null  str
 10  price       206774 non-null  str
 11  Date        206774 non-null  object
 12  Month       206774 non-null  object
 13  Year        206774 non-null  object
dtypes: int64(1), object(3), str(10)
memory usage: 22.1+ MB

In [154]:
df['Date'] = df['Date'].astype(int)
df['Month'] = df['Month'].astype(int)
df['Year'] = df['Year'].astype(int)

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 206774 entries, 0 to 206773
Data columns (total 14 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   date        206774 non-null  str
 1   airline     206774 non-null  str
 2   ch_code     206774 non-null  str
 3   num_code    206774 non-null  int64
 4   dep_time    206774 non-null  str
 5   from        206774 non-null  str
 6   time_taken  206774 non-null  str
 7   stop        206774 non-null  str
 8   arr_time    206774 non-null  str
 9   to          206774 non-null  str
 10  price       206774 non-null  str
 11  Date        206774 non-null  int64
 12  Month       206774 non-null  int64
 13  Year        206774 non-null  int64
dtypes: int64(4), str(10)
memory usage: 22.1 MB

In [155]:
# Drop the original 'date' column as we have extracted the necessary information
df.drop('date', axis=1, inplace=True)

In [156]:
df.head()

,airline,ch_code,num_code,dep_time,from,time_taken,stop,arr_time,to,price,Date,Month,Year
0,SpiceJet,SG,8709,18:55,Delhi,02h 10m,non-stop,21:05,Mumbai,"5,953",11,2,2022
1,SpiceJet,SG,8157,06:20,Delhi,02h 20m,non-stop,08:40,Mumbai,"5,953",11,2,2022
2,AirAsia,I5,764,04:25,Delhi,02h 10m,non-stop,06:35,Mumbai,"5,956",11,2,2022
3,Vistara,UK,995,10:20,Delhi,02h 15m,non-stop,12:35,Mumbai,"5,955",11,2,2022
4,Vistara,UK,963,08:50,Delhi,02h 20m,non-stop,11:10,Mumbai,"5,955",11,2,2022

In [157]:
df['Arrival_hour'] = df['arr_time'].str.split(':').str[0].astype(int)
df['Arrival_minute'] = df['arr_time'].str.split(':').str[1].astype(int)
df.head()

,airline,ch_code,num_code,dep_time,from,time_taken,stop,arr_time,to,price,Date,Month,Year,Arrival_hour,Arrival_minute
0,SpiceJet,SG,8709,18:55,Delhi,02h 10m,non-stop,21:05,Mumbai,"5,953",11,2,2022,21,5
1,SpiceJet,SG,8157,06:20,Delhi,02h 20m,non-stop,08:40,Mumbai,"5,953",11,2,2022,8,40
2,AirAsia,I5,764,04:25,Delhi,02h 10m,non-stop,06:35,Mumbai,"5,956",11,2,2022,6,35
3,Vistara,UK,995,10:20,Delhi,02h 15m,non-stop,12:35,Mumbai,"5,955",11,2,2022,12,35
4,Vistara,UK,963,08:50,Delhi,02h 20m,non-stop,11:10,Mumbai,"5,955",11,2,2022,11,10

In [158]:
# Drop the original 'arr_time' column as we have extracted the necessary information
df.drop('arr_time', axis=1, inplace=True)

df.head()

,airline,ch_code,num_code,dep_time,from,time_taken,stop,to,price,Date,Month,Year,Arrival_hour,Arrival_minute
0,SpiceJet,SG,8709,18:55,Delhi,02h 10m,non-stop,Mumbai,"5,953",11,2,2022,21,5
1,SpiceJet,SG,8157,06:20,Delhi,02h 20m,non-stop,Mumbai,"5,953",11,2,2022,8,40
2,AirAsia,I5,764,04:25,Delhi,02h 10m,non-stop,Mumbai,"5,956",11,2,2022,6,35
3,Vistara,UK,995,10:20,Delhi,02h 15m,non-stop,Mumbai,"5,955",11,2,2022,12,35
4,Vistara,UK,963,08:50,Delhi,02h 20m,non-stop,Mumbai,"5,955",11,2,2022,11,10

In [159]:
# departure time feature engineering

df['Departure_hour'] = df['dep_time'].str.split(':').str[0].astype(int)
df['Departure_minute'] = df['dep_time'].str.split(':').str[1].astype(int)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 206774 entries, 0 to 206773
Data columns (total 16 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   airline           206774 non-null  str
 1   ch_code           206774 non-null  str
 2   num_code          206774 non-null  int64
 3   dep_time          206774 non-null  str
 4   from              206774 non-null  str
 5   time_taken        206774 non-null  str
 6   stop              206774 non-null  str
 7   to                206774 non-null  str
 8   price             206774 non-null  str
 9   Date              206774 non-null  int64
 10  Month             206774 non-null  int64
 11  Year              206774 non-null  int64
 12  Arrival_hour      206774 non-null  int64
 13  Arrival_minute    206774 non-null  int64
 14  Departure_hour    206774 non-null  int64
 15  Departure_minute  206774 non-null  int64
dtypes: int64(8), str(8)
memory usage: 25.2 MB

In [160]:
# Drop the original 'dep_time' column as we have extracted the necessary information
df.drop('dep_time', axis=1, inplace=True)
df.head()

,airline,ch_code,num_code,from,time_taken,stop,to,price,Date,Month,Year,Arrival_hour,Arrival_minute,Departure_hour,Departure_minute
0,SpiceJet,SG,8709,Delhi,02h 10m,non-stop,Mumbai,"5,953",11,2,2022,21,5,18,55
1,SpiceJet,SG,8157,Delhi,02h 20m,non-stop,Mumbai,"5,953",11,2,2022,8,40,6,20
2,AirAsia,I5,764,Delhi,02h 10m,non-stop,Mumbai,"5,956",11,2,2022,6,35,4,25
3,Vistara,UK,995,Delhi,02h 15m,non-stop,Mumbai,"5,955",11,2,2022,12,35,10,20
4,Vistara,UK,963,Delhi,02h 20m,non-stop,Mumbai,"5,955",11,2,2022,11,10,8,50

In [161]:
# Time taken for the flight feature engineering

# Extract the numeric parts safely using regex
df['time_taken_hours'] = df['time_taken'].str.extract(r'(\d+)\s*h')
df['time_taken_minutes'] = df['time_taken'].str.extract(r'(\d+)\s*m')

# Convert using capital "Int64" which allows NaN/Missing values natively
df['time_taken_hours'] = df['time_taken_hours'].astype('Int64')
df['time_taken_minutes'] = df['time_taken_minutes'].astype('Int64')


df.head(10)

,airline,ch_code,num_code,from,time_taken,stop,to,price,Date,Month,Year,Arrival_hour,Arrival_minute,Departure_hour,Departure_minute,time_taken_hours,time_taken_minutes
0,SpiceJet,SG,8709,Delhi,02h 10m,non-stop,Mumbai,"5,953",11,2,2022,21,5,18,55,2,10
1,SpiceJet,SG,8157,Delhi,02h 20m,non-stop,Mumbai,"5,953",11,2,2022,8,40,6,20,2,20
2,AirAsia,I5,764,Delhi,02h 10m,non-stop,Mumbai,"5,956",11,2,2022,6,35,4,25,2,10
3,Vistara,UK,995,Delhi,02h 15m,non-stop,Mumbai,"5,955",11,2,2022,12,35,10,20,2,15
4,Vistara,UK,963,Delhi,02h 20m,non-stop,Mumbai,"5,955",11,2,2022,11,10,8,50,2,20
5,Vistara,UK,945,Delhi,02h 20m,non-stop,Mumbai,"5,955",11,2,2022,14,0,11,40,2,20
6,Vistara,UK,927,Delhi,02h 05m,non-stop,Mumbai,"6,060",11,2,2022,11,35,9,30,2,5
7,Vistara,UK,951,Delhi,02h 10m,non-stop,Mumbai,"6,060",11,2,2022,16,30,14,20,2,10
8,GO FIRST,G8,334,Delhi,02h 10m,non-stop,Mumbai,"5,954",11,2,2022,10,10,8,0,2,10
9,GO FIRST,G8,336,Delhi,02h 15m,non-stop,Mumbai,"5,954",11,2,2022,16,35,14,20,2,15

In [162]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 206774 entries, 0 to 206773
Data columns (total 17 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   airline             206774 non-null  str
 1   ch_code             206774 non-null  str
 2   num_code            206774 non-null  int64
 3   from                206774 non-null  str
 4   time_taken          206774 non-null  str
 5   stop                206774 non-null  str
 6   to                  206774 non-null  str
 7   price               206774 non-null  str
 8   Date                206774 non-null  int64
 9   Month               206774 non-null  int64
 10  Year                206774 non-null  int64
 11  Arrival_hour        206774 non-null  int64
 12  Arrival_minute      206774 non-null  int64
 13  Departure_hour      206774 non-null  int64
 14  Departure_minute    206774 non-null  int64
 15  time_taken_hours    206774 non-null  Int64
 16  time_taken_minutes  206770 non-null  Int64
dtypes: Int64(2), int64(8), str(7)
memory usage: 27.2 MB

In [163]:
# Drop the original 'time_taken' column as we have extracted the necessary information
df.drop('time_taken', axis=1, inplace=True)

In [164]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 206774 entries, 0 to 206773
Data columns (total 16 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   airline             206774 non-null  str
 1   ch_code             206774 non-null  str
 2   num_code            206774 non-null  int64
 3   from                206774 non-null  str
 4   stop                206774 non-null  str
 5   to                  206774 non-null  str
 6   price               206774 non-null  str
 7   Date                206774 non-null  int64
 8   Month               206774 non-null  int64
 9   Year                206774 non-null  int64
 10  Arrival_hour        206774 non-null  int64
 11  Arrival_minute      206774 non-null  int64
 12  Departure_hour      206774 non-null  int64
 13  Departure_minute    206774 non-null  int64
 14  time_taken_hours    206774 non-null  Int64
 15  time_taken_minutes  206770 non-null  Int64
dtypes: Int64(2), int64(8), str(6)
memory usage: 25.6 MB

In [165]:
# convert the 'price' column to numeric type, handling any non-numeric values

df['price'] = df['price'].str.replace(',', '').astype(float)

In [166]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 206774 entries, 0 to 206773
Data columns (total 16 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   airline             206774 non-null  str
 1   ch_code             206774 non-null  str
 2   num_code            206774 non-null  int64
 3   from                206774 non-null  str
 4   stop                206774 non-null  str
 5   to                  206774 non-null  str
 6   price               206774 non-null  float64
 7   Date                206774 non-null  int64
 8   Month               206774 non-null  int64
 9   Year                206774 non-null  int64
 10  Arrival_hour        206774 non-null  int64
 11  Arrival_minute      206774 non-null  int64
 12  Departure_hour      206774 non-null  int64
 13  Departure_minute    206774 non-null  int64
 14  time_taken_hours    206774 non-null  Int64
 15  time_taken_minutes  206770 non-null  Int64
dtypes: Int64(2), float64(1), int64(8), str(5)
memory usage: 25.6 MB

In [167]:
df.head()

,airline,ch_code,num_code,from,stop,to,price,Date,Month,Year,Arrival_hour,Arrival_minute,Departure_hour,Departure_minute,time_taken_hours,time_taken_minutes
0,SpiceJet,SG,8709,Delhi,non-stop,Mumbai,5953.0,11,2,2022,21,5,18,55,2,10
1,SpiceJet,SG,8157,Delhi,non-stop,Mumbai,5953.0,11,2,2022,8,40,6,20,2,20
2,AirAsia,I5,764,Delhi,non-stop,Mumbai,5956.0,11,2,2022,6,35,4,25,2,10
3,Vistara,UK,995,Delhi,non-stop,Mumbai,5955.0,11,2,2022,12,35,10,20,2,15
4,Vistara,UK,963,Delhi,non-stop,Mumbai,5955.0,11,2,2022,11,10,8,50,2,20

In [168]:
df['stop'] = df['stop'].str.strip()

df['stop'].unique()

<StringArray>
[                                          'non-stop',
                                             '1-stop',
            '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia IXU',
        '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Chennai',
         '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Indore',
            '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia RPR',
                                            '2+-stop',
        '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Lucknow',
            '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia GOP',
         '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Raipur',
         '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Nagpur',
          '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Surat',
      '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Hyderabad',
            '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia STV',
            '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia IDR',
            '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia VTZ',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Guwahati',
            '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia NAG',
 '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Vishakhapatnam',
            '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia NDC',
            '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia IXE',
          '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Patna',
            '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia PAT',
      '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Mangalore',
         '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Mumbai',
            '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia KLH',
            '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia MYQ',
        '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Kolkata',
          '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Delhi',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Kolhapur',
            '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia JRG',
    '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Bhubaneswar',
         '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Ranchi',
            '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia IXR',
            '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia JGB',
            '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia BBI',
         '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Mysore']
Length: 37, dtype: str

In [169]:
# Clean the stop value
def clean_stop(stop):
    if (stop == 'non-stop'):
        return '0'
    else:
        return stop[0]

df['stops'] = df['stop'].apply(clean_stop)

df.tail()

,airline,ch_code,num_code,from,stop,to,price,Date,Month,Year,Arrival_hour,Arrival_minute,Departure_hour,Departure_minute,time_taken_hours,time_taken_minutes,stops
206769,Vistara,UK,832,Chennai,1-stop,Hyderabad,7697.0,31,3,2022,20,55,7,5,13,50,1
206770,Vistara,UK,832,Chennai,1-stop,Hyderabad,7709.0,31,3,2022,20,55,7,5,13,50,1
206771,Vistara,UK,826,Chennai,1-stop,Hyderabad,8640.0,31,3,2022,9,5,12,30,20,35,1
206772,Vistara,UK,822,Chennai,1-stop,Hyderabad,8640.0,31,3,2022,9,5,9,45,23,20,1
206773,Vistara,UK,824,Chennai,1-stop,Hyderabad,8640.0,31,3,2022,20,55,20,30,24,25,1

In [170]:
df['stops'] = df['stops'].astype(int)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 206774 entries, 0 to 206773
Data columns (total 17 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   airline             206774 non-null  str
 1   ch_code             206774 non-null  str
 2   num_code            206774 non-null  int64
 3   from                206774 non-null  str
 4   stop                206774 non-null  str
 5   to                  206774 non-null  str
 6   price               206774 non-null  float64
 7   Date                206774 non-null  int64
 8   Month               206774 non-null  int64
 9   Year                206774 non-null  int64
 10  Arrival_hour        206774 non-null  int64
 11  Arrival_minute      206774 non-null  int64
 12  Departure_hour      206774 non-null  int64
 13  Departure_minute    206774 non-null  int64
 14  time_taken_hours    206774 non-null  Int64
 15  time_taken_minutes  206770 non-null  Int64
 16  stops               206774 non-null  int64
dtypes: Int64(2), float64(1), int64(9), str(5)
memory usage: 27.2 MB

In [171]:
df.drop('stop', axis=1, inplace=True)

In [172]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 206774 entries, 0 to 206773
Data columns (total 16 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   airline             206774 non-null  str
 1   ch_code             206774 non-null  str
 2   num_code            206774 non-null  int64
 3   from                206774 non-null  str
 4   to                  206774 non-null  str
 5   price               206774 non-null  float64
 6   Date                206774 non-null  int64
 7   Month               206774 non-null  int64
 8   Year                206774 non-null  int64
 9   Arrival_hour        206774 non-null  int64
 10  Arrival_minute      206774 non-null  int64
 11  Departure_hour      206774 non-null  int64
 12  Departure_minute    206774 non-null  int64
 13  time_taken_hours    206774 non-null  Int64
 14  time_taken_minutes  206770 non-null  Int64
 15  stops               206774 non-null  int64
dtypes: Int64(2), float64(1), int64(9), str(4)
memory usage: 25.6 MB

In [173]:
df.head()

,airline,ch_code,num_code,from,to,price,Date,Month,Year,Arrival_hour,Arrival_minute,Departure_hour,Departure_minute,time_taken_hours,time_taken_minutes,stops
0,SpiceJet,SG,8709,Delhi,Mumbai,5953.0,11,2,2022,21,5,18,55,2,10,0
1,SpiceJet,SG,8157,Delhi,Mumbai,5953.0,11,2,2022,8,40,6,20,2,20,0
2,AirAsia,I5,764,Delhi,Mumbai,5956.0,11,2,2022,6,35,4,25,2,10,0
3,Vistara,UK,995,Delhi,Mumbai,5955.0,11,2,2022,12,35,10,20,2,15,0
4,Vistara,UK,963,Delhi,Mumbai,5955.0,11,2,2022,11,10,8,50,2,20,0

In [174]:
# Data Preprocessing 
df['airline'].unique()

from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder()

encoded_df = pd.DataFrame(encoder.fit_transform(df[['airline', 'from', 'to']]).toarray(), columns=encoder.get_feature_names_out(['airline', 'from', 'to'])).head()

df = df.join(encoded_df)

df.head()

,airline,ch_code,num_code,from,to,price,Date,Month,Year,Arrival_hour,...,from_Delhi,from_Hyderabad,from_Kolkata,from_Mumbai,to_Bangalore,to_Chennai,to_Delhi,to_Hyderabad,to_Kolkata,to_Mumbai
0,SpiceJet,SG,8709,Delhi,Mumbai,5953.0,11,2,2022,21,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,SpiceJet,SG,8157,Delhi,Mumbai,5953.0,11,2,2022,8,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,AirAsia,I5,764,Delhi,Mumbai,5956.0,11,2,2022,6,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,Vistara,UK,995,Delhi,Mumbai,5955.0,11,2,2022,12,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,Vistara,UK,963,Delhi,Mumbai,5955.0,11,2,2022,11,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [175]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 206774 entries, 0 to 206773
Data columns (total 36 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   airline             206774 non-null  str
 1   ch_code             206774 non-null  str
 2   num_code            206774 non-null  int64
 3   from                206774 non-null  str
 4   to                  206774 non-null  str
 5   price               206774 non-null  float64
 6   Date                206774 non-null  int64
 7   Month               206774 non-null  int64
 8   Year                206774 non-null  int64
 9   Arrival_hour        206774 non-null  int64
 10  Arrival_minute      206774 non-null  int64
 11  Departure_hour      206774 non-null  int64
 12  Departure_minute    206774 non-null  int64
 13  time_taken_hours    206774 non-null  Int64
 14  time_taken_minutes  206770 non-null  Int64
 15  stops               206774 non-null  int64
 16  airline_Air India   5 non-null       float64
 17  airline_AirAsia     5 non-null       float64
 18  airline_GO FIRST    5 non-null       float64
 19  airline_Indigo      5 non-null       float64
 20  airline_SpiceJet    5 non-null       float64
 21  airline_StarAir     5 non-null       float64
 22  airline_Trujet      5 non-null       float64
 23  airline_Vistara     5 non-null       float64
 24  from_Bangalore      5 non-null       float64
 25  from_Chennai        5 non-null       float64
 26  from_Delhi          5 non-null       float64
 27  from_Hyderabad      5 non-null       float64
 28  from_Kolkata        5 non-null       float64
 29  from_Mumbai         5 non-null       float64
 30  to_Bangalore        5 non-null       float64
 31  to_Chennai          5 non-null       float64
 32  to_Delhi            5 non-null       float64
 33  to_Hyderabad        5 non-null       float64
 34  to_Kolkata          5 non-null       float64
 35  to_Mumbai           5 non-null       float64
dtypes: Int64(2), float64(21), int64(9), str(4)
memory usage: 57.2 MB

In [176]:
# Remove the original categorical columns after encoding
df.drop(['airline', 'from', 'to'], axis=1, inplace=True)

In [177]:
df.head()

,ch_code,num_code,price,Date,Month,Year,Arrival_hour,Arrival_minute,Departure_hour,Departure_minute,...,from_Delhi,from_Hyderabad,from_Kolkata,from_Mumbai,to_Bangalore,to_Chennai,to_Delhi,to_Hyderabad,to_Kolkata,to_Mumbai
0,SG,8709,5953.0,11,2,2022,21,5,18,55,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,SG,8157,5953.0,11,2,2022,8,40,6,20,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,I5,764,5956.0,11,2,2022,6,35,4,25,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,UK,995,5955.0,11,2,2022,12,35,10,20,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,UK,963,5955.0,11,2,2022,11,10,8,50,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [178]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 206774 entries, 0 to 206773
Data columns (total 33 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ch_code             206774 non-null  str
 1   num_code            206774 non-null  int64
 2   price               206774 non-null  float64
 3   Date                206774 non-null  int64
 4   Month               206774 non-null  int64
 5   Year                206774 non-null  int64
 6   Arrival_hour        206774 non-null  int64
 7   Arrival_minute      206774 non-null  int64
 8   Departure_hour      206774 non-null  int64
 9   Departure_minute    206774 non-null  int64
 10  time_taken_hours    206774 non-null  Int64
 11  time_taken_minutes  206770 non-null  Int64
 12  stops               206774 non-null  int64
 13  airline_Air India   5 non-null       float64
 14  airline_AirAsia     5 non-null       float64
 15  airline_GO FIRST    5 non-null       float64
 16  airline_Indigo      5 non-null       float64
 17  airline_SpiceJet    5 non-null       float64
 18  airline_StarAir     5 non-null       float64
 19  airline_Trujet      5 non-null       float64
 20  airline_Vistara     5 non-null       float64
 21  from_Bangalore      5 non-null       float64
 22  from_Chennai        5 non-null       float64
 23  from_Delhi          5 non-null       float64
 24  from_Hyderabad      5 non-null       float64
 25  from_Kolkata        5 non-null       float64
 26  from_Mumbai         5 non-null       float64
 27  to_Bangalore        5 non-null       float64
 28  to_Chennai          5 non-null       float64
 29  to_Delhi            5 non-null       float64
 30  to_Hyderabad        5 non-null       float64
 31  to_Kolkata          5 non-null       float64
 32  to_Mumbai           5 non-null       float64
dtypes: Int64(2), float64(21), int64(9), str(1)
memory usage: 52.5 MB

In [179]:
# Drop the ch_code column as it is not useful for prediction
df.drop('ch_code', axis=1, inplace=True)

In [180]:
# So finally we have the following features in our dataset:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 206774 entries, 0 to 206773
Data columns (total 32 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   num_code            206774 non-null  int64
 1   price               206774 non-null  float64
 2   Date                206774 non-null  int64
 3   Month               206774 non-null  int64
 4   Year                206774 non-null  int64
 5   Arrival_hour        206774 non-null  int64
 6   Arrival_minute      206774 non-null  int64
 7   Departure_hour      206774 non-null  int64
 8   Departure_minute    206774 non-null  int64
 9   time_taken_hours    206774 non-null  Int64
 10  time_taken_minutes  206770 non-null  Int64
 11  stops               206774 non-null  int64
 12  airline_Air India   5 non-null       float64
 13  airline_AirAsia     5 non-null       float64
 14  airline_GO FIRST    5 non-null       float64
 15  airline_Indigo      5 non-null       float64
 16  airline_SpiceJet    5 non-null       float64
 17  airline_StarAir     5 non-null       float64
 18  airline_Trujet      5 non-null       float64
 19  airline_Vistara     5 non-null       float64
 20  from_Bangalore      5 non-null       float64
 21  from_Chennai        5 non-null       float64
 22  from_Delhi          5 non-null       float64
 23  from_Hyderabad      5 non-null       float64
 24  from_Kolkata        5 non-null       float64
 25  from_Mumbai         5 non-null       float64
 26  to_Bangalore        5 non-null       float64
 27  to_Chennai          5 non-null       float64
 28  to_Delhi            5 non-null       float64
 29  to_Hyderabad        5 non-null       float64
 30  to_Kolkata          5 non-null       float64
 31  to_Mumbai           5 non-null       float64
dtypes: Int64(2), float64(21), int64(9)
memory usage: 50.9 MB